### ISSUE TITLE
多GPU训练

### ISSUE THREAD

**Issue by yuwan-codediary** [lartpang/ZoomNeXt#13]
作者你好，十分感谢你的开源，我的单张GPU显存不够用，我想问问您的代码如何使用多GPU进行训练，我直接model =torch.nn.DataParallel(model,devices_id=[0,1])会报错，请问您有用多GPU训练过吗？如果有的话可以告知我如何修改吗，十分感谢您

**Comment by lartpang** [comment]
@yuwan-codediary 
不好意思，我并没有尝试过多GPU训练的情况。
不过你可以把报错信息贴上来，我可以帮你看看 :>。

**Comment by yuwan-codediary** [comment]
十分感谢您的回复，很抱歉这么晚才回复您

model = model_class(num_frames=cfg.num_frames, pretrained=cfg.pretrained, use_checkpoint=cfg.use_checkpoint)
# model.to(cfg.device)
model = torch.nn.DataParallel(model,device_ids=[0,3]).cuda()
您的代码是注释的，放在单一GPU上训练，我是用这个model = torch.nn.DataParallel(model,device_ids=[0,3]).cuda()进行多GPU训练会报错误如下，而使用单一GPU训练的话，也就是使用您的代码是可以正常运行的，使用多GPU报错如下：


/home/YuhuaZhang2024/anaconda3/envs/Zoom/lib/python3.9/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "/data/yhz2024/code/Zoom/ZoomNeXt-main/my_main_for_video_select_3.py", line 703, in <module>
    main()
  File "/data/yhz2024/code/Zoom/ZoomNeXt-main/my_main_for_video_select_3.py", line 692, in main
    train(model=model, cfg=cfg)
  File "/data/yhz2024/code/Zoom/ZoomNeXt-main/my_main_for_video_select_3.py", line 502, in train
    scaler.calculate_grad(loss=loss)
  File "/data/yhz2024/code/Zoom/ZoomNeXt-main/utils/pipeline/scaler.py", line 24, in calculate_grad
    self.scaler.scale(loss).backward()
  File "/home/YuhuaZhang2024/anaconda3/envs/Zoom/lib/python3.9/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/YuhuaZhang2024/anaconda3/envs/Zoom/lib/python3.9/site-packages/torch/autograd/__init__.py", line 244, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_, is_grads_batched=False)
  File "/home/YuhuaZhang2024/anaconda3/envs/Zoom/lib/python3.9/site-packages/torch/autograd/__init__.py", line 117, in _make_grads
    raise RuntimeError(
RuntimeError: grad can be implicitly created only for scalar outputs

**Comment by yuwan-codediary** [comment]
您好，我已经解决了这个问题，其实只需要修改loss = outputs["loss"]成loss = outputs["loss"].mean() 和几处model.xxx修改成model.module.xxx即可，但是此时输出的loss_str 变成图片这样子了
<img width="1366" alt="image" src="https://github.com/user-atta
<img width="669" alt="微信图片_20241205193144" src="https://github.com/user-attachments/assets/b8a173d6-76de-4af9-a2bb-46cba8add2a8">
chments/assets/abe9f6ba-4db7-4b4e-8c58-43826ac05064">

**Comment by lartpang** [comment]
@yuwan-codediary 

😅 这个问题还是第一次见，感觉类似于你这里的计算均值，这里的最终输出是并不是一个独立的数字或者独立的字符串了，可能涉及到了多个部分？（这点我不清楚，只是一个直观的猜测，建议你打印出来看看）

**Comment by erobernLi** [comment]
> 您好，我已经解决了这个问题，其实只需要修改loss = outputs["loss"]成loss = outputs["loss"].mean() 和几处model.xxx修改成model.module.xxx即可，但是此时输出的loss_str 变成图片这样子了 <img width="1366" alt="image" src="https://github.com/user-atta <img alt="微信图片_20241205193144" width="669" src="https://private-user-images.githubusercontent.com/101965553/392793124-b8a173d6-76de-4af9-a2bb-46cba8add2a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcyNjA4OTAsIm5iZiI6MTczNzI2MDU5MCwicGF0aCI6Ii8xMDE5NjU1NTMvMzkyNzkzMTI0LWI4YTE3M2Q2LTc2ZGUtNGFmOS1hMmJiLTQ2Y2JhOGFkZDJhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExOVQwNDIzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWYzM2VjNDQwYzQ3OTcyMzcwNzFhNDg3ZmQ4NTUyMTQ5YjlkNDFkYTBhOWZkZWJkMDhkODU3NDdmNTg1ZmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1-Fg1Z1GScg4wEy0bYYPjKATaIAqLmpiU7tNRl9UJjo"> chments/assets/abe9f6ba-4db7-4b4e-8c58-43826ac05064">

您好，我也在进行多gpu训练，我能否询问您具体修改了哪些地方？我将几处model.xxx修改为了model.module.xxx，没有修改loss，但是代码一直在loss的上一行报错，即下图中的outputs所在行。

![Image](https://github.com/user-attachments/assets/9b191281-464b-48c1-a84b-c541faf686de)

报错信息如下图所示

![Image](https://github.com/user-attachments/assets/be05c99b-7974-4a5a-a6c4-df19f9ce3883)

我想咨询您是否碰到过此问题？您在我的报错行是否做出过什么改动？十分感谢。

**Comment by yuwan-codediary** [comment]
你好，刚刚看到你的信息，我查看了之前的代码，并没有遇到你这个问题，我并没有对你图片里的内容进行修改，没能帮到你很抱歉

<img width="801" alt="Image" src="https://github.com/user-attachments/assets/699722bf-e7f2-4833-bbdf-4d6757906d34" />
